# Generated by Django 4.2.6 on 2023-10-16 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=50, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=50, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=2, null=True, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=2, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=2, null=True, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=2, null=True, verbose_name='Весна')),
            ],
            options={
                'verbose_name': 'Категория трудности',
                'verbose_name_plural': 'Категория трудности',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otc', models.CharField(max_length=50, verbose_name='Отчество')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(default=None, max_length=255, verbose_name='Форма рельефа')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Альтернативное название')),
                ('connect', models.TextField(blank=True, null=True, verbose_name='Соединяет')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('new', 'новый объект'), ('pending', 'объект рассматривается'), ('accepted', 'объект принят'), ('rejected', 'отказано')], default='new', max_length=10, verbose_name='Статус объекта')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perevalmounts.coords')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perevalmounts.level')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perevalmounts.user')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевал',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.URLField(blank=True, null=True, verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='perevalmounts.pereval')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
