# Generated by Django 4.2.6 on 2023-10-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalmounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='E-mail'),
        ),
    ]
