# Generated by Django 4.2.6 on 2023-10-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalmounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, verbose_name='E-mail'),
        ),
    ]
